### ISSUE TITLE
a question of loading checkpoints

### ISSUE THREAD

**Issue by uuz21181522** [whai362/PVTv2-Seg#3]
Hello
I try to run the dist_test.sh and use [pvt_v2_b2.pth as pretrained ckeckpoints] and [configs/sem_fpn/PVTv2/fpn_pvtv2_b2_ade20k_40k.py] but get an error:
Traceback (most recent call last):
  File "./test.py", line 159, in <module>
Traceback (most recent call last):
  File "./test.py", line 159, in <module>
    main()
  File "./test.py", line 127, in main
    main()
  File "./test.py", line 127, in main
    model.CLASSES = checkpoint['meta']['CLASSES']
    KeyErrormodel.CLASSES = checkpoint['meta']['CLASSES']:
'meta'
KeyError: 'meta'

And the model and loaded state dict do not match exactly too.

**Comment by mahmoudtarek1871997** [comment]
I have this issue too, any help?

**Comment by mahmoudtarek1871997** [comment]
I think that the provided pretrained checkpoints are just the pretrained backbones (without the segmentation head), I tried to eval pvt v1 tiny and it worked perfectly resulting the ~36 miou cited at the paper, correct me if i am wrong.
